version: '3'

services:
  nginx:
    image: nginx:stable
    volumes:
      - ".:/var/www/html:rw"
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    restart: "unless-stopped"
    ports:
      - "80:80"

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
      - .:/data
    restart: "on-failure"
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fabrica

  petshop:
    depends_on:
      - db
    build:
      context: docker/petshop
    volumes:
      - .:/var/www/html:rw
    ports:
      - "8000:80"
    restart: "on-failure"
    environment:
      XDEBUG_CONFIG: client_host=192.168.0.178
      PHP_IDE_CONFIG: serverName=localhost

volumes:
  db_data:
    driver: local