version: '3'

services:
  nginx:
    image: nginx:stable
    volumes:
      - ".:/var/www/html:rw"
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    restart: "unless-stopped"
    ports:
      - "80:80"

  petshop:
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: docker/petshop
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        UNAME: ${UNAME:-docker}
    volumes:
      - .:/var/www/html:rw
    ports:
      - "8000:80"
    restart: "on-failure"
    environment:
      XDEBUG_CONFIG: client_host=192.168.0.178
      PHP_IDE_CONFIG: serverName=localhost